use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :blog_engine, BlogEngineWeb.Endpoint,
  http: [port: 4075],
  # https: [
  #   port: 4061,
  #   cipher_suite: :strong,
  #   keyfile: "priv/cert/selfsigned_key.pem",
  #   certfile: "priv/cert/selfsigned.pem"
  # ],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :blog_engine, BlogEngineWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(html|js|css|png|jpeg|jpg|gif|svg)$",
      ~r"lib/blog_engine/.*(ex)$",
      ~r"lib/blog_engine_web/.*(ex)$",
      ~r"lib/blog_engine_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :blog_engine, url: System.get_env("ENDPOINT")

# config :blog_engine, :revenue_monster,
#   key: System.get_env("RM_API_KEY"),
#   endpoint: System.get_env("RM_API_ENDPOINT"),
#   callback: System.get_env("RM_API_CALLBACK_URL"),
#   oauth: System.get_env("RM_AUTH_API"),
#   client_id: System.get_env("RM_CLIENT_ID"),
#   client_secret: System.get_env("RM_CLIENT_SECRET"),
#   private_key: System.get_env("RM_CLIENT_PRIVATE_KEY"),
#   cert_location: "/priv/cert/private_key.pem"
config :blog_engine, :mbos_api, System.get_env("MBOS_API")
config :blog_engine, :ipay88, callback: System.get_env("IPAY88_CALLBACK")
config :blog_engine, release: :dev

config :blog_engine, :revenue_monster,
  prefix: "TST",
  key: System.get_env("RM_API_KEY_PROD"),
  endpoint: System.get_env("RM_API_ENDPOINT_PROD"),
  callback: System.get_env("RM_API_CALLBACK_URL"),
  oauth: System.get_env("RM_AUTH_API_PROD"),
  client_id: System.get_env("RM_CLIENT_ID_PROD"),
  client_secret: System.get_env("RM_CLIENT_SECRET_PROD"),
  private_key: System.get_env("RM_CLIENT_PRIVATE_KEY_PROD"),
  cert_location: "/priv/cert/private_key_prod.pem"

config :blog_engine, :billplz,
  key: System.get_env("BILLPLZ_API_KEY"),
  endpoint: System.get_env("BILLPLZ_API_ENDPOINT"),
  callback: System.get_env("BILLPLZ_API_CALLBACK_URL")

config :blog_engine, :razer,
  vkey: System.get_env("RAZER_VKEY"),
  mid: System.get_env("RAZER_MID"),
  endpoint: System.get_env("RAZER_ENDPOINT")

config :blog_engine, BlogEngine.Mailer, adapter: Bamboo.LocalAdapter
